### ISSUE TITLE
Formatting doesn't use the .swift-format file as described in the swift-format docs

### ISSUE THREAD

**Issue by gpambrozio** [ruiaureliano/X-SwiftFormat#12]
According to [the swift-format docs](https://github.com/apple/swift-format#configuration):

> Configuration
> For any source file being checked or formatted, swift-format looks for a JSON-formatted file named .swift-format in the same directory. If one is found, then that file is loaded to determine the tool's configuration. If the file is not found, then it looks in the parent directory, and so on.
> 

I have such a file on my project root but when using the plugin to reformat my sources it uses the configuration in X-SwiftFormat instead of the configuration in the file.

**Comment by ruiaureliano** [comment]
X-SwiftFormat uses the internal configuration, which is the way we developed this. We need a way to import the `.swift-format`, that's the issue #11
