### ISSUE TITLE
Why a custom formatter file?

### ISSUE THREAD

**Issue by ScottRobbins** [ruiaureliano/X-SwiftFormat#13]
In a recent version the ability was added to export a `.swift-format` file, which is really useful because that's what the command-line swift-format utility uses. Given this app is mainly a utility around that utility, why not just use the `.swift-format` file as the configuration file? 

The duplication of these formatting rules seems like it isn't necessary.

**Comment by ruiaureliano** [comment]
I was not aware that rules could be included as an entry of the` .swift-format` file.

This make sense

**Comment by ruiaureliano** [comment]
@ScottRobbins fixed for `1.0.2`

**Comment by ScottRobbins** [comment]
Thanks for looking into that so quickly!
