### ISSUE TITLE
Homebrew installation support or AppStore

### ISSUE THREAD

**Issue by L1cardo** [ruiaureliano/X-SwiftFormat#14]
It would be nice to have homebrew installation support. 
We can install using 
```bash
brew cask install x-swiftformat
```

Or going on AppleStore is the best

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ruiaureliano** [comment]
We decided to remove the app from appstore, curious how we add this to cask? 

Sip is listed there, but it was not me :)

![i](https://user-images.githubusercontent.com/435699/84263064-b440d780-ab16-11ea-9746-f873f0815c8e.png)

**Comment by L1cardo** [comment]
Adding to cask is super easy and need someone to update when there is a new version.
But what is that Sip ?

**Comment by ruiaureliano** [comment]
Its another app that I build https://sipapp.io, and it's listed there, and it was not me, so I asked how we add this.

**Comment by L1cardo** [comment]
I can add this to cask, and when you release a new version you need to update the cask.
Adding to cask needs to pull a request to cask repo, and this is super easy!

**Comment by L1cardo** [comment]
Or if X-SwiftFormat can go on Apple Store, it will be the best option!

**Comment by ruiaureliano** [comment]
That's too much time consuming, this is a free app, I want to spend the free time developing the app and not explaining to apple reviewers why this is needed :)

**Comment by L1cardo** [comment]
> That's too much time consuming, this is a free app, I want to spend the free time developing the app and not explaining to apple reviewers why this is needed :)

OK then, cask will do

**Comment by L1cardo** [comment]
![image](https://user-images.githubusercontent.com/33802186/84454943-90a09d00-ac8e-11ea-8ded-96171f2ca6cf.png)
 now we can install using `brew cask install x-swiftformat`
