### ISSUE TITLE
How Rules take action in  X-SwiftFormat

### ISSUE THREAD

**Issue by kingnight** [ruiaureliano/X-SwiftFormat#17]
hi,

## What I have done

-  Follow ReadMe enable X-SwiftFormat
-  Download swift-format
```
swift-format --version
0.50200.1
```

## Question 
![x-swiftformat rule](https://github.com/kingnight/ImagesBed/blob/master/x-swiftformat.png)
For Example  ， Rules
- [ ] Always use Lower camel case ,checked
- [ ]  Order Imports,checked
```
var TestInput: String = ""
```
-  TestInput stared with T, not followed  Lower camel case, but  no format or warning 
-   Rules ： Order Imports  ， format right
So What‘s the difference ？How Rules Take Action in Xcode when Editor-X-SwiftFormat-Format Swift Code，Why Some Rules Take action, do any steps I miss?

**Comment by ruiaureliano** [comment]
Thanks @kingnight seem like an issue for swift-format, will report
