### ISSUE TITLE
X-SwiftFormat doesn't show up in Settings > Extensions > Xcode Source Editor

### ISSUE THREAD

**Issue by andreyz** [ruiaureliano/X-SwiftFormat#19]
Installed via `brew cask`, even restarted the system. No luck.

**Comment by ruiaureliano** [comment]
What's your xcode version?

**Comment by andreyz** [comment]
Tried with Xcode 11.6 and 12 beta 5. Neither works. Xcode 11.6 is the active toolchain.

**Comment by ruiaureliano** [comment]
I had the same issue because I had both at the same time Xcode 11 and Xcode 12Beta. What I did was rename the Xcode app to **XCode-11**, the system will ask you to authorize that, then renamed back to **XCode** .

Restarted my mac and all was working fine

**Comment by andreyz** [comment]
That was it! I had my apps named Xcode-11.6 and Xcode-12-beta5 when I ran X-SwiftFormat for the first time. After renaming Xcode 11-6 to Xcode, X-SwiftFormat appeared in the Source Extensions.

Didn't even require a restart.
