### ISSUE TITLE
Open file doesn't work as expected

### ISSUE THREAD

**Issue by davidrothera** [ruiaureliano/X-SwiftFormat#22]
The default file used for `swift-format` is `.swift-format` however at the moment the open dialog doesn't work with this and since https://github.com/ruiaureliano/X-SwiftFormat/commit/ec9c13d684c90a29077bb8ce4819509e98196683 requires the file to be suffixed with `swift-format` (e.g. `foo.swift-format`) which sounds wrong; we should allow any file really.

**Comment by mefilt** [comment]
??

**Comment by iletai** [comment]
I facing same issues, I confirm open dialog could not open `.swiftformat` file in MacOS Vetunal. Try many way to fix. Any update here. Just getle remind here. It's should be reopen

**Comment by FPT-TaiLQT** [comment]
Facing same issues

> (e.g. `foo.swift-format`)

Special thanks to @davidrothera . I fixed by temp set for that name. It's very helpful when someone doesn't find the actual reason.

**Comment by iletai** [comment]
> (e.g. `foo.swift-format`)

Special thanks to @davidrothera . I fixed by temp set for that name. It's very helpful when someone doesn't find the actual reason.
