### ISSUE TITLE
Always adds line break before first argument

### ISSUE THREAD

**Issue by Igor-Palaguta** [ruiaureliano/X-SwiftFormat#3]
```swift
let a = A(first: 1,
          second: 2)
```
transforms to:
```swift
let a = A(
          first: 1,
          second: 2)
```

**Comment by ruiaureliano** [comment]
Hey @Igor-Palaguta thanks for the feedback, we are using this as our core Formatter & Syntax

https://github.com/apple/swift-format
https://github.com/apple/swift-syntax

This is something that we can't fix :)

Rui
