### ISSUE TITLE
Adds extra linebreak in return statement

### ISSUE THREAD

**Issue by Igor-Palaguta** [ruiaureliano/X-SwiftFormat#4]
```swift
      return SwifQL
         .select()
```
transforms to:
```swift
      return
          SwifQL
          .select()
```

**Comment by ruiaureliano** [comment]
Hey @Igor-Palaguta thanks for the feedback, we are using this as our core Formatter & Syntax

https://github.com/apple/swift-format
https://github.com/apple/swift-syntax

This is something that we can't fix :)

Rui

**Comment by Igor-Palaguta** [comment]
@ruiaureliano 

Yes looks like apple's swift-format is on early stage

But this https://github.com/nicklockwood/SwiftFormat looks amazing
