### ISSUE TITLE
Keep indents on empty line

### ISSUE THREAD

**Issue by javierugarte** [ruiaureliano/X-SwiftFormat#5]
Is it possible to add an option to keep the indent on the empty lines?

Or does it exist?

![ezgif-4-7455bb99fa56](https://user-images.githubusercontent.com/2904339/78552241-6b635e80-7807-11ea-9f08-8e54ba648084.gif)

**Comment by ruiaureliano** [comment]
@javierugarte unfortunately, this is something that can only be changed here:
> https://github.com/apple/swift-format
