### ISSUE TITLE
Add new line after each method

### ISSUE THREAD

**Issue by haashem** [ruiaureliano/X-SwiftFormat#6]
Is it possible to configure it to add a new line after each method?

BEFORE:
<img width="416" alt="Screen Shot 2020-04-09 at 2 56 27 PM" src="https://user-images.githubusercontent.com/3206748/78885879-8f76a800-7a72-11ea-8d71-341ab3b0df7a.png">

AFTER:
<img width="473" alt="Screen Shot 2020-04-09 at 2 56 41 PM" src="https://user-images.githubusercontent.com/3206748/78885899-97cee300-7a72-11ea-9c05-a375e342391c.png">

**Comment by ruiaureliano** [comment]
@hashemp206 unfortunately, this is something that can only be changed here:
> https://github.com/apple/swift-format
