### ISSUE TITLE
App should support export configurations into json/xml files

### ISSUE THREAD

**Issue by p-z-l** [ruiaureliano/X-SwiftFormat#8]
This allows us to share configs with other teammates to make sure that the code format stays the same throughout the entire project.

Also, I think multiple profiles could be helpful as well.

**Comment by ruiaureliano** [comment]
I will set a custom file for `configuration` and `rules`, probably
> `.xsf-config`
> `.xsf-rules`
thanks @p-z-l

**Comment by ruiaureliano** [comment]
I will set a custom file for `configuration` and `rules`, probably

> `.xsfconfig`
> `.xsfrules`

thanks @p-z-l

**Comment by ruiaureliano** [comment]
It now open and save `.xsfconfig` and `.xsfrules` files

![config@2x](https://user-images.githubusercontent.com/435699/80023956-3ed16700-84d6-11ea-8abc-07657e70b8a3.png)

![rules@2x](https://user-images.githubusercontent.com/435699/80023961-4133c100-84d6-11ea-897a-1992ef6b0296.png)
