### ISSUE TITLE
Xcode stops responding when formatting

### ISSUE THREAD

**Issue by ScottRobbins** [ruiaureliano/X-SwiftFormat#9]
If I run X-Swift-Format on my project Xcode stops responding and beachballs. Sometimes after a while (30 seconds to a minute) it unfreezes, but other times it stays in that state and I need to force-quit. Swift format I can run from the command line without an issue though. 

Haven't had a chance yet to get a reproducible project, but I'm curious if anyone else is experiencing this.

Xcode 11.4.1, Catalina 10.15.4

**Comment by ruiaureliano** [comment]
@ScottRobbins, I saw this a few times, we are using https://github.com/apple/swift-format this for the foundation, maybe some rule that's breaking.

Can you share more about the file that you're trying to format? size, things that you think its relevant

Thanks

**Comment by ScottRobbins** [comment]
I made the repo public here: https://github.com/SwiftBuildTools/Codesign 

The xsconfigs are in the repo. It freezes when I try to run it on the `SignCommand.swift` file.

**Comment by ruiaureliano** [comment]
Ok thanks, will check, also just noted that you have a `.swift-format` file, now its possible export directly from the app.

<img width="815" alt="app" src="https://user-images.githubusercontent.com/435699/80400680-0bfee880-88b3-11ea-9445-f1abcb79cec2.png">

**Comment by ruiaureliano** [comment]
@ScottRobbins also noted that you have this `lineLength : 80`, which is a bit aggressive but should work.

**Comment by ScottRobbins** [comment]
Glad to see the .swift-format export! Is that something that will be available in an upcoming release? (Don't see it in 1.0)

> also noted that you have this lineLength : 80, which is a bit aggressive but should work.

I agree, I'll probably change it back to 100.

**Comment by ruiaureliano** [comment]
@ScottRobbins the performance issue has been fixed in version 1.0.1 👍

☛ Download [here](https://github.com/ruiaureliano/X-SwiftFormat/releases/download/1.0.1/x-swiftformat_1.0.1_.2000501.zip)

**Comment by ScottRobbins** [comment]
Works great, thank you @ruiaureliano !
